version: '3'
services:
  app:
    container_name: insert2redis
    image: insert2redis:v1
    build: .
    links:
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ~/docker/redis:/insert2redis/logs
  redis:
    container_name: redis
    image: redis:latest
    build: ./redis
    hostname: redis
    ports:
      - "6379:6379"
