spring:
  application:
    name: redis-service

  redis:
    port: 6379
    password: 123456
    host: afshin
    timeToLive: 60

logging:
  file:
    path: redis-service/logs
  level:
    com.rkdevblog.redis: DEBUG
